import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/components/layouts/navbar";

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
